### ISSUE TITLE
Improve main content vertical centering

### ISSUE THREAD

**Issue by jpcody** [mateoclarke/wikipedia-exercise#1]
How could we change the vertical centering of the main content so it were more resilient to content changes and staying centered?

**Comment by mateoclarke** [comment]
Can you give me a little more info or a screenshot? I'm seeing it stay centered vertically in the page no matter the size of the window or the amount of content I add. 

I didn't optimize for mobile but I don't think you're asking for any media queries. 

![screen shot 2015-04-21 at 8 05 01 pm](https://cloud.githubusercontent.com/assets/5697474/7265614/0f62a1e8-e862-11e4-86ed-89f697f3a15a.png)

**Comment by jpcody** [comment]
Derp. I was totally wrong. Carry on!
