### ISSUE TITLE
Tooltip position is off

### ISSUE THREAD

**Issue by jpcody** [mateoclarke/wikipedia-exercise#2]
![](http://d.pr/i/1bL3d.png)

For me, the positioning of the tooltips are off. I'm hovering on the far-right tooltip.

[Here are my browser details](http://d.pr/f/2V79).

**Comment by mateoclarke** [comment]
I promise my tooltips worked when I originally deployed. But one bug fix led to another bug surfacing...

![image](http://i.giphy.com/8WdsK61D9YOOc.gif)

I was using `.prepend($('.timeline-point'))` to add the tooltips to the DOM wherever there was a `div.timeline-point` in the hover state. Then the tooltip was repositioned to the right spot with the `.css({top: y, left: x})` method based on some measurements I was grabbing with jQuery. This all fell apart whenever I switched the way I was centering the main content with the Sass mixin. It seemed like the absolute position of this main content box was throwing off the relative values I was grabbing.

Now I'm appending each tooltip to the `<body>` tag and repositioning them based on position of the purple dot relative to the whole page. Much cleaner.

**Comment by mateoclarke** [comment]
Please reopen if you see the same issue.

**Comment by jpcody** [comment]
Awesome, thank you for the explanation. I've faced a similar problem before. Leaving the tooltip where it is can also cause its containing element to clip it if the containing element has `overflow: hidden` set on it. So I think you came to the right solution that moving it to the end minimizes side effects.
