### ISSUE TITLE
Switch to radial gradient for the background

### ISSUE THREAD

**Issue by jpcody** [mateoclarke/wikipedia-exercise#3]
It's not immediately obvious in the mocks, but this is actually a radial gradient. How would you solve bringing that in line with the mock?

**Comment by mateoclarke** [comment]
It's still kind of hard to see :eyes: on my monitor but I've started to address this issue. I used [Compass docs](http://compass-style.org/examples/compass/css3/gradient/) for reference.

**Comment by jpcody** [comment]
:ok_hand:!
